apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronik-operator
  namespace: chronik-operator-system
  labels:
    app.kubernetes.io/name: chronik-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: chronik-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chronik-operator
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chronik-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/part-of: chronik-stream
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: chronik-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: operator
        image: chronik/operator:latest
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/chronik-operator
        env:
        - name: RUST_LOG
          value: "info,chronik_operator=debug"
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: "chronik-operator"
        ports:
        - name: http-metrics
          containerPort: 8080
          protocol: TCP
        - name: http-health
          containerPort: 8081
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http-health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http-health
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      terminationGracePeriodSeconds: 30