apiVersion: v1
kind: ServiceAccount
metadata:
  name: chronik-operator
  namespace: chronik-operator-system
  labels:
    app.kubernetes.io/name: chronik-operator
    app.kubernetes.io/component: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chronik-operator
  labels:
    app.kubernetes.io/name: chronik-operator
    app.kubernetes.io/component: operator
rules:
# ChronikCluster CRD permissions
- apiGroups: ["chronik.stream"]
  resources: ["chronikclusters"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["chronik.stream"]
  resources: ["chronikclusters/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["chronik.stream"]
  resources: ["chronikclusters/finalizers"]
  verbs: ["update"]

# Core resources
- apiGroups: [""]
  resources: ["configmaps", "services", "serviceaccounts", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

# Apps resources
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Policy resources
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Autoscaling resources
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# RBAC resources
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# CRD management
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chronik-operator
  labels:
    app.kubernetes.io/name: chronik-operator
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chronik-operator
subjects:
- kind: ServiceAccount
  name: chronik-operator
  namespace: chronik-operator-system