apiVersion: v1
kind: Service
metadata:
  name: chronik-operator-metrics
  namespace: chronik-operator-system
  labels:
    app.kubernetes.io/name: chronik-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: chronik-stream
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/name: chronik-operator
    app.kubernetes.io/component: operator
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  - name: http-health
    port: 8081
    targetPort: http-health
    protocol: TCP
  type: ClusterIP