services:
  controller:
    build:
      context: .
      dockerfile: deploy/docker/controller.Dockerfile
    environment:
      METADATA_PATH: /data/metadata
      NODE_ID: 1
      RUST_LOG: info
    volumes:
      - controller_metadata:/data/metadata
    ports:
      - "9090:9090"
    user: root

volumes:
  controller_metadata:
EOF < /dev/null