version: '3.8'

services:
  # TiKV Cluster for testing - advertises localhost instead of Docker hostnames
  pd0:
    image: pingcap/pd:latest
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      CLUSTER_SIZE: 1
    command:
      - --name=pd0
      - --data-dir=/data/pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://localhost:2379
      - --advertise-peer-urls=http://localhost:2380
      - --initial-cluster=pd0=http://localhost:2380
      - --force-new-cluster=true
    volumes:
      - pd0_test_data:/data

  tikv0:
    image: pingcap/tikv:latest
    ports:
      - "20160:20160"
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=localhost:20160
      - --data-dir=/data/tikv0
      - --pd=localhost:2379
    volumes:
      - tikv0_test_data:/data
    depends_on:
      - pd0

  tikv1:
    image: pingcap/tikv:latest
    ports:
      - "20161:20160"
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=localhost:20161
      - --data-dir=/data/tikv1
      - --pd=localhost:2379
    volumes:
      - tikv1_test_data:/data
    depends_on:
      - pd0

  tikv2:
    image: pingcap/tikv:latest
    ports:
      - "20162:20160"
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=localhost:20162
      - --data-dir=/data/tikv2
      - --pd=localhost:2379
    volumes:
      - tikv2_test_data:/data
    depends_on:
      - pd0

volumes:
  pd0_test_data:
  tikv0_test_data:
  tikv1_test_data:
  tikv2_test_data: