version: '3.8'

services:
  chronik:
    image: ghcr.io/lspecian/chronik-stream:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    volumes:
      - chronik-data:/data
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  chronik-data:
    driver: local
