# Example secret for PostgreSQL credentials
# In production, use external secret managers like Vault or Sealed Secrets
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  # username: chronik
  username: Y2hyb25paw==
  # password: changeme
  password: Y2hhbmdlbWU=