apiVersion: chronik.stream/v1alpha1
kind: ChronikCluster
metadata:
  name: chronik-demo
  namespace: chronik-system
spec:
  controllers: 3
  ingestNodes: 5
  storage:
    backend:
      s3:
        bucket: chronik-segments
        region: us-east-1
    size: 100Gi
    storageClass: gp3
  metastore:
    database: Postgres
    connection:
      host: postgres.chronik-system.svc.cluster.local
      port: 5432
      database: chronik_metastore
      credentialsSecret: postgres-credentials
  resources:
    controller:
      cpu: "1"
      memory: "2Gi"
      cpuLimit: "2"
      memoryLimit: "4Gi"
    ingest:
      cpu: "2"
      memory: "4Gi"
      cpuLimit: "4"
      memoryLimit: "8Gi"
  image:
    controller: chronik/controller:v0.1.0
    ingest: chronik/ingest:v0.1.0
    pullPolicy: IfNotPresent
  monitoring:
    prometheus: true
    tracing: true
    otlpEndpoint: jaeger-collector.monitoring:4317