enabled = true
node_id = 3
replication_factor = 3
min_insync_replicas = 2

[[peers]]
id = 1
addr = "127.0.0.1:9092"
raft_port = 5001

[[peers]]
id = 2
addr = "127.0.0.1:9093"
raft_port = 5002

[[peers]]
id = 3
addr = "127.0.0.1:9094"
raft_port = 5003
