apiVersion: chronik.stream/v1alpha1
kind: ChronikCluster
metadata:
  name: basic-cluster
  namespace: chronik-stream
spec:
  controllers: 3
  ingestNodes: 3
  searchNodes: 3
  storage:
    backend: local
    size: "10Gi"
  metastore:
    database: postgres
    connection:
      host: postgres
      port: 5432
      database: chronik
      credentialsSecret: postgres-secret