apiVersion: chronik.stream/v1alpha1
kind: ChronikCluster
metadata:
  name: production-cluster
  namespace: chronik-stream
  labels:
    environment: production
spec:
  controllers: 5
  ingestNodes: 6
  searchNodes: 4
  
  storage:
    backend: s3
    s3:
      bucket: chronik-production-data
      region: us-west-2
      endpoint: null
    size: "100Gi"
    storageClass: fast-ssd
  
  metastore:
    database: postgres
    connection:
      host: postgres-cluster.database.svc.cluster.local
      port: 5432
      database: chronik_prod
      credentialsSecret: postgres-credentials
  
  resources:
    controller:
      cpu: "2"
      memory: "4Gi"
      cpuLimit: "4"
      memoryLimit: "8Gi"
    ingest:
      cpu: "4"
      memory: "8Gi"
      cpuLimit: "8"
      memoryLimit: "16Gi"
    search:
      cpu: "2"
      memory: "4Gi"
      cpuLimit: "4"
      memoryLimit: "8Gi"
  
  image:
    controller: chronik/controller:v1.0.0
    ingest: chronik/ingest:v1.0.0
    search: chronik/search:v1.0.0
    pullPolicy: IfNotPresent
    pullSecrets:
      - regcred
  
  monitoring:
    prometheus: true
    tracing: true
    otlpEndpoint: http://jaeger-collector:14268/api/traces
  
  network:
    serviceType: LoadBalancer
    loadBalancerSourceRanges:
      - 10.0.0.0/8
      - 172.16.0.0/12
  
  security:
    tlsEnabled: true
    tlsSecret: chronik-tls
    mtlsEnabled: true
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      runAsNonRoot: true
    containerSecurityContext:
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
  
  autoscaling:
    controllers:
      minReplicas: 3
      maxReplicas: 10
      targetCpuUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    ingestNodes:
      minReplicas: 3
      maxReplicas: 20
      targetCpuUtilizationPercentage: 60
      targetMemoryUtilizationPercentage: 70
    searchNodes:
      minReplicas: 2
      maxReplicas: 15
      targetCpuUtilizationPercentage: 75
      targetMemoryUtilizationPercentage: 85
  
  podDisruptionBudget:
    minAvailable: 50%
  
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
  
  podLabels:
    app.kubernetes.io/name: chronik-stream
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/component: distributed-stream-processor
  
  nodeSelector:
    node-type: compute-optimized
  
  tolerations:
    - key: chronik-dedicated
      operator: Equal
      value: "true"
      effect: NoSchedule
  
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - us-west-2a
                  - us-west-2b
                  - us-west-2c
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - chronik-stream
            topologyKey: kubernetes.io/hostname