[build]
jobs = 8
incremental = true
target-dir = "target"

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "target-cpu=x86-64-v2",
    "-C", "opt-level=2",
]

[target.aarch64-unknown-linux-musl]
rustflags = [
    "-C", "target-cpu=generic",
    "-C", "opt-level=2",
]

[profile.dev]
opt-level = 0
debug = 0
incremental = true
overflow-checks = false

[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = 2
lto = "thin"
codegen-units = 16
incremental = true
strip = true
panic = "abort"

[profile.release-fast]
inherits = "release"
opt-level = 2
lto = false
codegen-units = 256

[profile.release-optimized]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1