# Chronik Raft Cluster Configuration - Node 1

[server]
# Kafka port
kafka_port = 9091
bind_addr = "0.0.0.0"
advertised_addr = "localhost"
advertised_port = 9091
data_dir = "./data/node1"

[cluster]
enabled = true
node_id = 1
replication_factor = 3
min_insync_replicas = 2

[cluster.peers]
# Static peer list (all nodes)
nodes = [
  { id = 1, addr = "localhost:9091" },
  { id = 2, addr = "localhost:9092" },
  { id = 3, addr = "localhost:9093" },
]

[raft]
# Raft ports are kafka_port + 100
listen_addr = "localhost:9101"

# Timing
election_timeout_ms = 1000
heartbeat_interval_ms = 100

# Snapshots
snapshot_max_log_size_mb = 64
snapshot_min_interval_entries = 10000

# Network
rpc_timeout_ms = 5000
max_inflight_messages = 256

[raft.advanced]
# ISR tracking
replica_lag_max_entries = 1000
replica_lag_max_ms = 10000

# Leadership
enable_leadership_transfer = true
leadership_transfer_timeout_ms = 5000
