# Multi-Datacenter Configuration for Chronik Raft
# Example configuration for a 3-datacenter deployment

[datacenter]
# Local datacenter configuration
id = "us-west-2a"
region = "us-west-2"
availability_zone = "a"
rack_id = "rack-1"
replication_mode = "local_sync"  # Options: local_sync, multi_dc_sync, async

# Node configuration
[node]
node_id = 1
listen_addr = "0.0.0.0:5001"
advertise_addr = "node1.us-west-2a.example.com:5001"

# Cluster topology
[[cluster.datacenters]]
id = "us-west-2a"
region = "us-west-2"
nodes = [
    { id = 1, host = "node1.us-west-2a.example.com", port = 5001, rack = "rack-1" },
    { id = 2, host = "node2.us-west-2a.example.com", port = 5002, rack = "rack-2" },
    { id = 3, host = "node3.us-west-2a.example.com", port = 5003, rack = "rack-1" },
]

[[cluster.datacenters]]
id = "us-east-1a"
region = "us-east-1"
nodes = [
    { id = 4, host = "node4.us-east-1a.example.com", port = 5001, rack = "rack-1" },
    { id = 5, host = "node5.us-east-1a.example.com", port = 5002, rack = "rack-2" },
    { id = 6, host = "node6.us-east-1a.example.com", port = 5003, rack = "rack-1" },
]

[[cluster.datacenters]]
id = "eu-west-1a"
region = "eu-west-1"
nodes = [
    { id = 7, host = "node7.eu-west-1a.example.com", port = 5001, rack = "rack-1" },
    { id = 8, host = "node8.eu-west-1a.example.com", port = 5002, rack = "rack-2" },
    { id = 9, host = "node9.eu-west-1a.example.com", port = 5003, rack = "rack-1" },
]

# Raft configuration for WAN deployment
[raft]
mode = "wan"  # Options: lan, wan
election_tick = 30
heartbeat_tick = 3
tick_interval_ms = 500
max_size_per_msg_mb = 10
max_inflight_msgs = 256
enable_compression = true
max_batch_size = 500
applied_index_check_interval_secs = 10

# Partition assignment configuration
[partitions]
replication_factor = 3
rack_aware = true
prefer_local_leader = true  # Place leaders in local DC for low write latency

# Replication modes explained:
# 
# local_sync (default):
#   - Synchronous replication within local DC
#   - Asynchronous replication to remote DCs
#   - Fast writes, high availability
#   - Risk: Data loss if DC fails before remote replication
#
# multi_dc_sync:
#   - Synchronous replication across N datacenters
#   - Wait for quorum in each datacenter
#   - Slower writes, strongest durability
#   - Survives complete DC failure with zero data loss
#
# async:
#   - Asynchronous replication to all DCs
#   - Fastest writes, lowest latency
#   - Risk: Possible data loss on DC failure

# Multi-DC sync configuration (only if replication_mode = "multi_dc_sync")
[multi_dc_sync]
min_dcs = 2  # Minimum datacenters for quorum
timeout_ms = 5000  # Timeout for cross-DC sync

# Monitoring
[monitoring]
enable_metrics = true
metrics_port = 9090
enable_cross_dc_lag_tracking = true
lag_warning_threshold_secs = 5.0
