name: Integration Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

env:
  RUST_BACKTRACE: 1
  RUST_LOG: chronik=debug,warn

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    services:
      # MinIO is started via testcontainers
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          libssl-dev \
          protobuf-compiler
    
    - name: Install test dependencies
      run: |
        # Install Docker (for testcontainers)
        curl -fsSL https://get.docker.com | sh
        sudo usermod -aG docker $USER
        
        # Install language runtimes for multi-language tests
        # Java
        sudo apt-get install -y openjdk-11-jdk maven
        
        # Python
        sudo apt-get install -y python3 python3-pip
        pip3 install kafka-python
        
        # Node.js
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        npm install -g kafkajs
    
    - name: Build project
      run: cargo build --all --release
    
    - name: Run unit tests
      run: cargo test --all --lib
    
    - name: Run integration tests
      run: |
        # Run tests one at a time to avoid port conflicts
        cargo test --test integration --release -- --test-threads=1
      env:
        RUST_LOG: chronik=debug,integration=debug
    
    - name: Run specific test suites
      run: |
        # Kafka compatibility tests
        cargo test --test integration kafka_compatibility -- --nocapture
        
        # Search integration tests  
        cargo test --test integration search_integration -- --nocapture
        
        # Failure recovery tests
        cargo test --test integration failure_recovery -- --nocapture
        
        # Performance tests (with relaxed thresholds for CI)
        cargo test --test integration performance -- --nocapture
      env:
        CI: true
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          target/debug/deps/*.json
          test-results/
    
    - name: Clean up Docker containers
      if: always()
      run: |
        docker ps -aq | xargs -r docker stop
        docker ps -aq | xargs -r docker rm
        docker volume prune -f

  performance-benchmarks:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          libssl-dev \
          protobuf-compiler
        
        # Install Docker
        curl -fsSL https://get.docker.com | sh
        sudo usermod -aG docker $USER
    
    - name: Run benchmarks
      run: |
        cargo bench --all
    
    - name: Store benchmark results
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'cargo'
        output-file-path: target/criterion/output.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true